FROM node:18.10.0-alpine

# curl needed to display Heroku release logs
RUN apk --no-cache add curl

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . /app
COPY .env.example /app/.env

RUN yarn build

CMD yarn start:prod
